name: Front-end-ci
on:
  push:
    branches-ignore:
      - main
jobs:
  ci:
    name: Unit and end-to-end tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies with install
        run: npm install

      - name: Install Dependencies with ci
        run: npm ci

      - name: Install Eslint
        run: npm install -g eslint

      - name: Install Prettier
        run: npm i -g prettier

      - name: Cache Cypress binary
        uses: cypress-io/github-action-cache@v2

      - name: Run ESLint
        run: npm run lint

      - name: Unit Tests
        run: npm test -- --watchAll=false  --passWithNoTests

      - name: Cypress.io
        uses: cypress-io/github-action@v5.7.1
        with:
          start: npm start
